# Generated by Django 5.2 on 2025-05-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
