# Generated by Django 5.2.1 on 2025-08-09 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0003_routinetracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routinetracker',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_tracker', to='routine.routine'),
        ),
    ]
