# Generated by Django 5.2.1 on 2025-08-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0004_alter_routinetracker_routine'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='privacy',
            field=models.BooleanField(default=False),
        ),
    ]
