# Generated by Django 5.2 on 2025-05-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_alter_profile_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
