# Generated by Django 5.2 on 2025-05-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_alter_follow_follower_alter_follow_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
